rank/models.py
# -*- coding: utf-8 -*-
"""Database module, including the SQLAlchemy database object and DB-related
utilities.
"""

from rank.api import models as api_models
from rank.user import models as user_models

gamecenter/user/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length

from gamecenter.user.models import User


class RegisterForm(Form):
    username = TextField('Username',
                         validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        return True

rank/user/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length

from rank.user.models import User


class RegisterForm(Form):
    username = TextField('Username',
                         validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        return True

gamecenter/user/views.py
# -*- coding: utf-8 -*-
"""User section, including dashboard."""
import arrow
from flask import render_template, jsonify, redirect, url_for, flash, request
from flask_login import login_required, current_user, logout_user

from . import blueprint
from gamecenter.api.models import UserRequest, Score
from gamecenter.api.schema import UserRequestSchema, ScoreSchema
from gamecenter.api.views import handle_api_key, get_unique_key
from gamecenter.core.models import DB
from gamecenter.core.utils import InvalidUsage
from gamecenter.user.models import User
from gamecenter.user.schema import UserSchema

REQUESTSCHEMA = UserRequestSchema()
SCORESCHEMA = ScoreSchema()
USERSCHEMA = UserSchema()


@blueprint.route("/")
@login_required
def dashboard():
    if current_user.is_admin:
        midnight = arrow.utcnow().replace(hour=0, minute=0, second=0, microsecond=0).datetime
        daily_reqs = UserRequest.query.filter(UserRequest.time_requested > midnight).count()
        api_keys = User.query.filter(User.is_admin == False).count()
        return render_template("user/admin/dashboard.html",
                               api_keys=api_keys,
                               expected_reqs=(api_keys*3600),
                               user_requests=daily_reqs)
    else:
        return render_template("user/dashboard.html")


@blueprint.route("/settings")
@login_required
def settings():
    if current_user.is_admin:
        users = [USERSCHEMA.dump(user).data for user in User.query.filter(User.is_admin == False)]
        return render_template("user/admin/impersonate.html",
                               users=users)
    else:
        return render_template("user/settings.html")


@blueprint.route("/resetkey", methods=['POST'])
@login_required
def reset_key():
    game = current_user.game
    game.api_key = get_unique_key()
    game.save()
    return redirect(url_for('user.settings'))


@blueprint.route("/deleteuser/<int:id>", methods=['POST'])
@login_required
def delete_user(id):
    if id == current_user.id:
        user = User.get_by_id(id)
        logout_user()
        user.delete()
        flash('Your account was successfully deleted.', 'info')
        return redirect(url_for('public.home'))
    if not current_user.is_admin:
        raise InvalidUsage('Forbidden', status_code=403)
    if id == current_user.id:
        raise InvalidUsage("You can't delete yourself!")
    user = User.query.filter(User.id == id).first()
    user.delete()
    return redirect(url_for('user.settings'))


@blueprint.route("/deletescores", methods=['POST'])
@login_required
def delete_scores():
    print request.form
    user_id = request.form['user_id']
    score_id = request.form['score_id']
    tag = request.form['tag']
    if user_id:
        scores = Score.query.filter(Score.game == current_user.game, Score.user_id == int(user_id))
        scores.delete()
    if score_id:
        score = Score.query.filter(Score.game == current_user.game, Score.id == int(score_id))
        score.delete()
    if tag:
        scores = Score.query.filter(Score.tag == tag, Score.game == current_user.game)
        scores.delete()
    DB.session.commit()
    return redirect(url_for('user.manage_data', user_id=current_user.id))


@blueprint.route("/togglefreeze/<int:user_id>", methods=['POST'])
@login_required
def freeze_user(user_id):
    if not current_user.is_admin:
        raise InvalidUsage('Forbidden', status_code=403)
    if user_id == current_user.id:
        raise InvalidUsage("You can't freeze yourself!")
    user = User.query.filter(User.id == user_id).first()
    user.game.frozen = not user.game.frozen
    user.game.save()
    return redirect(url_for('user.settings'))


@blueprint.route("/manage/<int:user_id>")
@login_required
def manage_data(user_id):
    user = current_user
    if user_id != user.id:
        if not current_user.is_admin:
            raise InvalidUsage("Forbidden", 403)
        user = User.get_by_id(user_id)
    return render_template(
        "user/managedata.html",
        scores=[SCORESCHEMA.dump(score).data for score in Score.query.filter(Score.game == user.game)])


@blueprint.route('/requests', methods=['GET'])
@handle_api_key
def requests_controller():
    weekly_reqs = [REQUESTSCHEMA.dump(req).data for req in current_user.requests_this_week()]
    daily_reqs = [REQUESTSCHEMA.dump(req).data for req in current_user.requests_today()]
    return jsonify(data={'weekly_reqs': weekly_reqs, 'daily_reqs': daily_reqs})

rank/__init__.py
MAJOR = 1
MINOR = 0
PATCH = 0

__version__ = "{0}.{1}.{2}".format(MAJOR, MINOR, PATCH)

rank/api/__init__.py
# -*- coding: utf-8 -*-
"""set up the API blueprint."""
from flask import Blueprint

blueprint = Blueprint('api', __name__, url_prefix="/api")

rank/api/views.py
# -*- coding: utf-8 -*-
"""API section."""
import datetime
import functools
import json
import random
import string

from flask import jsonify, request, g
from sqlalchemy.orm import scoped_session, sessionmaker

from . import blueprint
from rank.api.models import Score, Game
from rank.api.schema import ScoreSchema, UserRequestSchema
from rank.core.models import DB
from rank.core.utils import InvalidUsage
from rank.api.helpers.meta import get_meta_from_args
from rank.api.helpers.get import (
    get_request_args,
    construct_and_
)

SESSION = scoped_session(sessionmaker())
SCORESCHEMA = ScoreSchema()
REQUESTSCHEMA = UserRequestSchema()


def handle_api_key(f):
    @functools.wraps(f)
    def decorated_function(*args, **kwargs):
        if "Authorization" in request.headers:
            api_key = request.headers["Authorization"][7:]  # from the string form "Bearer <api_key>"
        else:
            api_key = ""
        game = Game.query.filter(Game.api_key == api_key).first()
        if game:
            if game.frozen:
                raise InvalidUsage("This account has been frozen.", 403)
            g.game = game
            return f(*args, **kwargs)
        else:
            raise InvalidUsage("Unable to authenticate you.", 401)
    return decorated_function


def create_game():
    game = Game(api_key=get_unique_key())
    DB.session.add(game)
    DB.session.commit()
    return game


def get_unique_key():
    chars = string.ascii_uppercase + string.digits
    length = 32

    key = ''.join(random.choice(chars) for _ in range(length))
    while Game.query.filter_by(api_key=key).first():
        key = ''.join(random.choice(chars) for _ in range(length))
    return key


@blueprint.route('/leaderboards', methods=['GET'])
@handle_api_key
@get_request_args
def leaderboards_controller(args):
    order = Score.score.desc()
    if args['sort'] == 'ascending':
        order = Score.score
    res_set = Score.query.order_by(order).filter(construct_and_(args))
    return scores_from_query(
        result_set=res_set.offset(args['offset'] - 1).limit(args['page_size']),
        args=args,
        endpoint='leaderboards',
        count=res_set.count(),
    )


@blueprint.route('/add_score', methods=['POST'])
@handle_api_key
def add_score_controller():
    return jsonify(data=SCORESCHEMA.dump(create_entry()).data)


@blueprint.route('/add_score_and_list', methods=['POST'])
@handle_api_key
@get_request_args
def add_score_and_list_controller(args):
    new_score = create_entry()
    order = Score.score.desc()
    if args['sort'] == 'ascending':
        order = Score.score
    del args['user_id']  # we don't want to filter based on this
    args['end_date'] = datetime.datetime.utcnow()  # so that the end date is after the new score's date

    if args['filter_tag'] not in (None, args['tag']):
        raise InvalidUsage("filter_tag must be either null or the same as the new score's tag")

    if args['radius'] is None:
        raise InvalidUsage("radius is required")

    q = Score.query.order_by(order).filter(construct_and_(args))
    q_results = q.all()
    new_score_index = (i for i, row in enumerate(q_results) if row.id == new_score.id).next()

    offset = max(0, new_score_index - args['radius'])
    return scores_from_query(
        result_set=q.offset(offset).limit(2 * args['radius'] + 1),
        args=args,
        endpoint='add_score_and_list',
    )


def create_entry():
    try:
        data = json.loads(request.data)
    except:
        raise InvalidUsage('Malformed JSON')
    data["game_id"] = g.game.id
    results, errors = SCORESCHEMA.load(data, session=SESSION)
    if errors:
        raise InvalidUsage(errors)

    DB.session.add(results)
    DB.session.commit()

    return results


def scores_from_query(result_set, args, endpoint, count=None):
    res = [SCORESCHEMA.dump(score).data for score in result_set]
    if count is None:
        count = len(res)
    return jsonify(data=res, meta=get_meta_from_args(count, args, endpoint))

rank/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
import logging

from flask import (
    current_app,
    Flask,
    g,
    jsonify,
    render_template,
    request,
)

from rank.api import views as api
from rank.api.models import Game
from rank.assets import assets
from rank.core import views as core
from rank.core.models import DB as db
from rank.core.utils import InvalidUsage
from rank.extensions import (
    cache,
    login_manager,
    migrate,
    debug_toolbar,
)
from rank.logger import (
    RankErrFilter,
    RankErrFormatter,
    RankFilter,
    RankFormatter,
    RankTimedRotatingFileHandler,
)
from rank.public import views as public
from rank.settings import ProdConfig
from rank.user import views as user


def create_app(config_object=ProdConfig):
    """An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)

    register_logger(app)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)

    @app.errorhandler(InvalidUsage)
    def handle_invalid_usage(error):
        """A handler for any endpoint that raises an InvalidUsage exception"""
        return jsonify(error.to_dict()), error.status_code

    @app.after_request
    def log_request(resp):
        """
        Create the log to send to the rotated log file
        """
        current_app.logger.info(str(resp.status_code))
        return resp

    @app.before_request
    def throttle():
        """
        Throttle the request if need be
        """
        if api.blueprint.url_prefix not in request.path:
            # don't need to throttle these requests
            return None
        if "Authorization" not in request.headers:
            # let somebody else handle this situation
            return None
        api_key = request.headers["Authorization"][7:]  # from the string form "Bearer <api_key>"
        game = Game.query.filter(Game.api_key == api_key).first()
        if not game:
            # let somebody else handle this situation
            return None
        g.game = game
        if game.user.request_count_today() >= app.config['THROTTLE_LIMIT']:
            return handle_invalid_usage(InvalidUsage("Exceeded maximum API requests.", 429))

    return app


def register_extensions(app):
    """Register the extensiosn of the app"""
    assets.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    """Register the routes of the app"""
    app.register_blueprint(public.blueprint)
    app.register_blueprint(api.blueprint)
    app.register_blueprint(core.blueprint)
    app.register_blueprint(user.blueprint)
    return None


def register_errorhandlers(app):
    """
    Set up the proper error handling things to do
    """
    def render_error(error):
        """
        Render the correct template based on the error code
        """
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_logger(app):
    """
    Initialize logging infrastructure based on the app environment
    """
    # remove the default handler
    app.logger.removeHandler(app.logger.handlers[0])
    # set the logger log level
    app.logger.setLevel(app.config['LOG_LEVEL'])

    # add a new handler and formatter to each of the loggers
    err_handler = RankTimedRotatingFileHandler(app.config['ERR_LOG'])
    err_handler.setLevel(logging.ERROR)
    err_handler.setFormatter(RankErrFormatter("%(message)s"))
    app.logger.addHandler(err_handler)
    err_handler.addFilter(RankErrFilter())

    handler = RankTimedRotatingFileHandler(app.config['LOG_FILE'])
    handler.setLevel(logging.DEBUG)
    handler.setFormatter(RankFormatter("%(message)s"))
    app.logger.addFilter(RankFilter())
    app.logger.addHandler(handler)
    return None

rank/core/__init__.py
from flask import Blueprint

blueprint = Blueprint('core', __name__)

rank/core/views.py
# -*- coding: utf-8 -*-
"""Core views."""
from flask import jsonify

from . import blueprint
from rank import __version__


@blueprint.route('/status')
def status_reporter():
    # be sure to include the version in this later
    return jsonify(status="ok", version=__version__)

rank/user/__init__.py
# -*- coding: utf-8 -*-
"""set up the user blueprint."""
from flask import Blueprint

blueprint = Blueprint('user', __name__, url_prefix="/dashboard", static_folder="../static")

rank/templates/user/admin/dashboard.html
{% extends "user/layout.html" %}

{% assets "admin_dash_css" %}
  <link rel="stylesheet" href="{{ ASSET_URL }}">
{% endassets %}

{% block content %}
<div class="card-wide mdl-card mdl-shadow--4dp mdl-color--blue-grey-500">
  <div class="mdl-card__title mdl-color-text--blue-grey-50">
    <h2 class="mdl-card__title-text">Active API Keys:</h2>
  </div>
  <div class="mdl-card__supporting-text request-card-content mdl-color-text--blue-grey-50">
    <h2 class="apikeys-card-count" id="active-keys">{{ api_keys }}</h2>
  </div>
</div>


<div class="card-wide mdl-card mdl-shadow--4dp">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text">Requests Made Today</h2>
  </div>
  <div class="mdl-card__supporting-text" id="requests-made-today">
    <h2>{{ user_requests }}</h2>
    out of an expected
    <h2>{{ expected_reqs }}</h2>
  </div>
</div>



{% endblock %}

rank/templates/user/admin/health.html
{% extends "user/layout.html" %}

{% block css %}
  {% assets "health_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}
{% endblock %}

{% block js %}
    <script src="//d3js.org/d3.v3.min.js"></script>
{% assets "overview_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock %}

{% block content %}
<div class="card-wide mdl-card mdl-shadow--4dp">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text">Request Frequency Breakdown</h2>
  </div>
  <div id="distribution-selection">
    <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="weekly">
      <input type="radio" id="weekly" class="mdl-radio__button" name="distribution-frequency" value="weekly" checked>
      <span class="mdl-radio__label">This Week</span>
    </label>
    <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="daily">
      <input type="radio" id="daily" class="mdl-radio__button" name="distribution-frequency" value="daily">
      <span class="mdl-radio__label">This Day</span>
    </label>
  </div>
  <div class="mdl-card__supporting-text request-card-content">
    <div id="weekly-chart"></div>
    <div id="daily-chart" class="hidden"></div>
  </div>
</div>

<div class="card-wide mdl-card mdl-shadow--4dp">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text">Server Health Link</h2>
  </div>
  <div class="mdl-card__supporting-text">
    For information on the server health link please <h5 class="inline"><a href="https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2">Consult the AWS Cloudwatch Console.</a></h5>
  </div>
</div>

{% endblock %}

rank/templates/user/admin/impersonate.html
{% extends "user/layout.html" %}

{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.css">
{% endblock %}

{% block content %}

<div class="mdl-card--colored mdl-shadow--4dp card-wide" id="data-table-card">
  <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" id="leaderboard-data-table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Requests Today</th>
        <th>Frozen?</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.requests_today }}</td>
        <td>{{ user.frozen }}</td>
        <td class="table-button">
          <form method="GET" action="{{ url_for('user.manage_data', user_id=user.id) }}">
            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--primary">View Data</button>
          </form>
        </td>
        <td class="table-button">
          <form method="POST" action="{{ url_for('user.freeze_user', user_id=user.id) }}">
            {% if user.frozen %}
              <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--primary">Unfreeze</button>
            {% else %}
              <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent">Freeze</button>
            {% endif %}
          </form>
        </td>
        <td class="table-button">
          <form method="POST" action="{{ url_for('user.delete_user', id=user.id) }}">
            <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent">DELETE</button>
          </form>
        </td>
        <td class="table-button">
          <form method="POST" action="{{ url_for('user.promote_to_admin', id=user.id) }}">
            <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent">Make Admin</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

{% block js %}
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
{% endblock %}